name: Auto Promote to Higher Environment

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - pre-staging
      - staging

jobs:
  promote:
      if: >
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'auto-promote-changes-till-prod')
      runs-on: ubuntu-latest
      
