name: Auto Promote to Higher Environment

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - pre-staging
      - staging

jobs:
  promote:
      if: >
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'auto-promote-changes-till-prod')
      runs-on: ubuntu-latest
      
      steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":rocket: A promotion PR was created from *${{ steps.set-branches.outputs.source }}* → *${{ steps.set-branches.outputs.target }}* and auto-merge was enabled."
            }
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
